In [1]:
import pandas as pd

In [22]:
df=pd.read_csv('EDA_done.csv')

In [23]:
df.head()

,Unnamed: 0,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Weather_conditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken (min),month,day,Final_Hour
0,0,36.0,4.2,30.327968,78.046106,30.397968,78.116106,4.0,1,2,2,3,3.0,0,3.0,46,2,12,22
1,1,21.0,4.7,10.003064,76.307589,10.043064,76.347589,1.0,2,1,3,3,1.0,0,3.0,23,2,13,15
2,2,23.0,4.7,18.562450,73.916619,18.652450,74.006619,2.0,3,1,1,2,1.0,0,3.0,21,3,4,17
3,3,34.0,4.3,30.899584,75.809346,30.919584,75.829346,2.0,4,0,4,3,0.0,0,3.0,20,2,13,9
4,4,24.0,4.7,26.463504,80.372929,26.593504,80.502929,4.0,1,1,2,2,1.0,0,3.0,41,2,14,20

In [43]:
df=df.iloc[:,1:]

In [6]:
df=df.drop(labels=['Delivery_person_ID'],axis=1)

In [44]:
df.head()

,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Weather_conditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken (min),month,day,Final_Hour
0,36.0,4.2,30.327968,78.046106,30.397968,78.116106,4.0,1,2,2,3,3.0,0,3.0,46,2,12,22
1,21.0,4.7,10.003064,76.307589,10.043064,76.347589,1.0,2,1,3,3,1.0,0,3.0,23,2,13,15
2,23.0,4.7,18.562450,73.916619,18.652450,74.006619,2.0,3,1,1,2,1.0,0,3.0,21,3,4,17
3,34.0,4.3,30.899584,75.809346,30.919584,75.829346,2.0,4,0,4,3,0.0,0,3.0,20,2,13,9
4,24.0,4.7,26.463504,80.372929,26.593504,80.502929,4.0,1,1,2,2,1.0,0,3.0,41,2,14,20

In [45]:
#Independent and dependent features
X=df.drop(labels=['Time_taken (min)'],axis=1)
Y=df[['Time_taken (min)']]

In [46]:
#Define which columns should be ordinal-encoded and which should be scaled
categorical_cols=X.select_dtypes(include='object').columns
numerical_cols=X.select_dtypes(exclude='object').columns

In [47]:
# Define the custom ranking for each ordinal variable
Weather_map=['Stormy','Sandstorms','windy','Fog','Cloudy','Sunny']
traffic_map=['Jam','High','Medium','Low']
vehicle_map=['electric_scooter','scooter','motorcycle']
order_map=['Drinks','Snack','Meal','Buffet']
festival_map=['No','Yes']
city_map=['Semi-urban','urban','Metropolitian']

In [48]:
from sklearn.impute import SimpleImputer #Handling Missing Values
from sklearn.preprocessing import StandardScaler #Handling Feature Scaling
from sklearn.preprocessing import OrdinalEncoder #Ordinal Encoding
##pipelines
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

In [49]:
#Numerical Pipeline
num_pipeline=Pipeline(
    steps=[
        ('imputer',SimpleImputer(strategy='median')),
        ('scalar',StandardScaler())
    ]
)
#Categorical Pipeline
cat_pipeline=Pipeline(
    steps=[
        ('imputer',SimpleImputer(strategy='most_frequent')),
        ('ordinalencoder',OrdinalEncoder(categories=[Weather_map,traffic_map,vehicle_map,order_map,festival_map,city_map])),
        ('scalar',StandardScaler())
    ]
)

preprocessor=ColumnTransformer([
    ('num_pipeline',num_pipeline,numerical_cols),
    ('cat_pipeline',cat_pipeline,categorical_cols)
])

In [50]:
numerical_cols

Index(['Delivery_person_Age', 'Delivery_person_Ratings', 'Restaurant_latitude',
       'Restaurant_longitude', 'Delivery_location_latitude',
       'Delivery_location_longitude', 'Weather_conditions',
       'Road_traffic_density', 'Vehicle_condition', 'Type_of_order',
       'Type_of_vehicle', 'multiple_deliveries', 'Festival', 'City', 'month',
       'day', 'Final_Hour'],
      dtype='object')

In [51]:
categorical_cols

Index([], dtype='object')

In [52]:
X

,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Weather_conditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,month,day,Final_Hour
0,36.0,4.2,30.327968,78.046106,30.397968,78.116106,4.0,1,2,2,3,3.0,0,3.0,2,12,22
1,21.0,4.7,10.003064,76.307589,10.043064,76.347589,1.0,2,1,3,3,1.0,0,3.0,2,13,15
2,23.0,4.7,18.562450,73.916619,18.652450,74.006619,2.0,3,1,1,2,1.0,0,3.0,3,4,17
3,34.0,4.3,30.899584,75.809346,30.919584,75.829346,2.0,4,0,4,3,0.0,0,3.0,2,13,9
4,24.0,4.7,26.463504,80.372929,26.593504,80.502929,4.0,1,1,2,2,1.0,0,3.0,2,14,20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43785,30.0,4.8,26.902328,75.794257,26.912328,75.804257,NaN,2,1,3,3,0.0,0,3.0,3,24,11
43786,21.0,4.6,0.000000,0.000000,0.070000,0.070000,NaN,1,0,4,3,1.0,0,3.0,2,16,20
43787,30.0,4.9,13.022394,80.242439,13.052394,80.272439,5.0,4,1,1,2,0.0,0,3.0,3,11,24
43788,20.0,4.7,11.001753,76.986241,11.041753,77.026241,5.0,2,0,2,3,1.0,0,3.0,3,7,13
43789,23.0,4.9,23.351058,85.325731,23.431058,85.405731,4.0,3,2,2,2,1.0,0,3.0,3,2,17

In [53]:
#Train test split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,Y,test_size=0.30,random_state=30)

In [54]:
X_train=pd.DataFrame(preprocessor.fit_transform(X_train),columns=preprocessor.get_feature_names_out())
X_test=pd.DataFrame(preprocessor.transform(X_test),columns=preprocessor.get_feature_names_out())

In [55]:
X_train.head()

,num_pipeline__Delivery_person_Age,num_pipeline__Delivery_person_Ratings,num_pipeline__Restaurant_latitude,num_pipeline__Restaurant_longitude,num_pipeline__Delivery_location_latitude,num_pipeline__Delivery_location_longitude,num_pipeline__Weather_conditions,num_pipeline__Road_traffic_density,num_pipeline__Vehicle_condition,num_pipeline__Type_of_order,num_pipeline__Type_of_vehicle,num_pipeline__multiple_deliveries,num_pipeline__Festival,num_pipeline__City,num_pipeline__month,num_pipeline__day,num_pipeline__Final_Hour
0,-0.102995,0.857730,0.703550,0.243835,0.717185,0.239736,-0.972548,1.115921,0.002079,0.449205,-0.785523,0.441097,-0.144858,0.0,0.03212,-1.472150,-1.777465
1,-0.278897,0.209337,1.046335,0.517975,1.101202,0.525800,0.206612,1.115921,1.227526,1.345189,0.772562,0.441097,-0.144858,0.0,-1.79794,0.482005,1.128548
2,0.600616,-0.114859,0.183172,0.147192,0.156226,0.141029,0.206612,1.115921,0.002079,-1.342763,-0.785523,-1.308507,-0.144858,0.0,0.03212,-0.092746,-1.569892
3,-0.454800,1.181927,0.035959,0.357295,0.012111,0.361847,0.206612,0.313596,0.002079,0.449205,-0.785523,0.441097,-0.144858,0.0,0.03212,-1.127299,-1.985037
4,-0.806605,1.181927,0.507635,0.101345,0.513642,0.096342,-1.562128,0.313596,0.002079,0.449205,0.772562,0.441097,-0.144858,0.0,0.03212,1.976359,-0.116886

In [56]:
#Model Training
from sklearn.linear_model import LinearRegression,Lasso,Ridge,ElasticNet
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error

In [57]:
regression=LinearRegression()
regression.fit(X_train,y_train)

LinearRegression()

In [58]:
regression.coef_

array([[ 2.16901047e+00, -2.37670890e+00, -2.09709617e-02,
         3.81968975e-01,  1.17468068e-01, -4.03826147e-01,
        -2.51661029e-01, -3.17974929e+00, -1.85083073e+00,
         3.59934858e-02,  1.19067192e-02,  2.01666114e+00,
         1.58760976e+00,  7.21644966e-16, -3.26629931e-02,
         7.38126056e-02,  5.70332097e-01]])

In [59]:
regression.intercept_

array([26.40994356])

In [60]:
import numpy as np
def evaluate_model(true, predicted):
    mae=mean_absolute_error(true,predicted)
    mse=mean_squared_error(true,predicted)
    rmse=np.sqrt(mean_squared_error(true,predicted))
    r2_square=r2_score(true,predicted)
    return mae,rmse,r2_square

In [61]:
#Train multiple models
models={
    'LinearRegression':LinearRegression(),
    'Lasso':Lasso(),
    'Ridge':Ridge(),
    'Elasticnet':ElasticNet()
}
trained_model_list=[]
model_list=[]
r2_list=[]
for i in range(len(list(models))):
    model=list(models.values())[i]
    model.fit(X_train,y_train)

    #Make Predictions
    y_pred=model.predict(X_test)

    mae,rmse,r2_square=evaluate_model(y_test,y_pred)
    print(list(models.keys())[i])
    model_list.append(list(models.keys())[i])

    print('Model Training Performance')
    print('RMSE:',rmse)
    print('MAE:',mae)
    print('R2 score',r2_square*100)

    r2_list.append(r2_square)
    print('='*35)
    print('\n')

LinearRegression
Model Training Performance
RMSE: 6.71371343993262
MAE: 5.351912982524015
R2 score 48.822500610795906
===================================


Lasso
Model Training Performance
RMSE: 7.068901753818024
MAE: 5.66144516387145
R2 score 43.26417786698487
===================================


Ridge
Model Training Performance
RMSE: 6.713712428852866
MAE: 5.351914159520214
R2 score 48.82251602537387
===================================


Elasticnet
Model Training Performance
RMSE: 7.176303234101106
MAE: 5.768075015450918
R2 score 41.52704742432687
===================================